package com.example.iron.mapper;

import com.example.iron.pojo.CaseGroupDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface CaseGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_group
     *
     * @mbg.generated Tue Jul 05 17:04:04 CST 2022
     */
    int insert(CaseGroupDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_group
     *
     * @mbg.generated Tue Jul 05 17:04:04 CST 2022
     */
    List<CaseGroupDO> selectAll();
}