spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iron?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
mybatis:
  type-aliases-package: com.example.iron.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml